# get the base node image
FROM node:alpine as builder

# set the working dir for container
WORKDIR /project

# copy the json file first
COPY ./package.json /project

# install npm dependencies
RUN yarn install

# copy other project files
COPY . .

EXPOSE 50054
# build the folder
CMD [ "yarn", "start:micro:project"]