# get the base node image
FROM node:alpine as builder

# set the working dir for container
WORKDIR /management

# copy the json file first
COPY ./package.json /management

# install npm dependencies
RUN yarn install

# copy other project files
COPY . .

EXPOSE 50055

# build the folder
CMD [ "yarn", "start:micro:management" ]